version: '3.7'

services:
#   bike_rental:
#     build: ./bike_rental
#     command: python ./bike_rental/db/models.py
#     network_mode: host
#   car_rental:
#     build: ./car_rental
#     command: python ./car_rental/app.py
#     network_mode: host
  postgres:
    image: postgres:11.4-alpine
    restart: always
    network_mode: host
    environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypass
        POSTGRES_DB: my_micro_db
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - ./local_test_data/postgres:/var/lib/postgresql/data